import type { Metadata } from "next";
import { GeistSans } from 'geist/font'
import { GeistMono } from 'geist/font'
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <main className={GeistMono.variable}>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  )
}

